config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'contacts' => 'pages#contacts'
  get 'caution' => 'pages#caution'
  resources :passings, only: %i(create) do
    get :results, action: :results, on: :member
  end

  resources :letters, only: %i(create)
  resources :questions, only: [] do
    resources :option_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :text_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :encouraged_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :attachment_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end
  end

  resources :episodes, only: [:index, :show] do
    resources :pages, only: [] do
      get :wait, on: :collection
    end
  end

  resources :tasks, only: [:show] do
    get :current, action: :current, on: :collection
  end

  resources :pages, only: [] do
    get :success, action: :success, on: :collection
    get :excuse, action: :excuse, on: :collection
    get :rules, action: :rules, on: :collection
  end



  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  authenticated :user do
    root "episodes#index", as: :authenticated_root
  end

  root to: 'pages#rules'
end

app/models/task.rb
class Task < ActiveRecord::Base
  acts_as_paranoid

  has_many :questions,  -> { order 'created_at asc' }, dependent: :destroy
  has_one :timer, dependent: :destroy

  has_many :passings
  has_many :attempts, dependent: :destroy

  belongs_to :episode
  validates :episode, :title, :content, presence: true

  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :timer, allow_destroy: true

#  delegate :text, :question_type, to: :question, allow_nil: true

  after_initialize :set_question
  after_initialize :set_timer
  before_validation :check_timer

  acts_as_list scope: :episode

  scope :completed, -> (user) { includes(:passings).where(passings: { user: user }) }
  scope :current, lambda { |user|
    return completed(user).last.lower_item if completed(user).present?

    first
  }

  def text
    self.questions.to_a
  end

  def question_type
    self.questions.to_a
  end

  def completed?(user)
    passings.where(user: user).size > 0
  end

  def not_expired?(user)
    timer.persisted? && ((DateTime.current.to_i - attempts.where(user: user)[0].created_at.to_i) < timer.value_in_minutes.minutes)
  end

  def current?(user)
    self.episode.current?(user) && self == self.episode.tasks.current(user)
  end

  def check_timer
    timer.delete if timer.value_in_minutes.blank?
  end

  def option_question
    OptionQuestion.where(task: self)[0]
  end

  def set_question
    build_questions unless questions
  end

  def set_timer
    build_timer unless timer
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def current
    excuse_page = Program.first
    current_episode = Episode.first
    Episode.active.find_each do |episode|
      break unless episode.completed?(current_user)
      current_episode = episode.lower_item
    end

    if current_episode.present? && current_episode.start_at && current_episode.start_at > DateTime.current
      return redirect_to wait_episode_pages_url(current_episode)
    end

    return redirect_to success_pages_url if current_episode.blank?

    if excuse_page.present? && excuse_page.start_time > DateTime.current
      return redirect_to excuse_pages_url
    end

    @task = current_episode.tasks.current(current_user)
    @passing = Passing.new
  end

  def show
    @task = Task.find(params[:id])
    if @task.questions.present?
      session[:questions] = @task.questions.sample(@task.questions_number)
      session[:qids] = session[:questions].map { |q| q.id}
      @attempt = Attempt.find_or_create_by(user: current_user, task: @task)
    end
  end
end

app/views/tasks/current.html.slim
.container.alerts
  .row
    .col-lg-12
      .bs-component
        - if @task.timer.persisted?
          div id="time-left"
            .alert.alert-danger.alert-dismissible.text-center
              button type="button" class="close" data-dismiss="alert"&times;
              p
                | Внимание! Это задание на время. На выполнение у вас &nbsp;
                strong
                  span.show-time-in-hours
                  span.show-time-in-minutes
                  span.show-time-in-seconds
          div id="time-is-out"
            .alert.alert-danger.alert-dismissible.text-center
              button type="button" class="close" data-dismiss="alert"&times;
              p
                | К сожалению,&nbsp;
                strong
                  | время на выполнение истекло.&nbsp;


.container
  .row
    .col-xs-12.col-sm-10.col-md-8.col-lg-8
        h2
          | Лекция&nbsp;
          = @task.position
          |.&nbsp;
          = @task.title

.container
  .row
    .col-xs-12.col-sm-10.col-md-8.col-lg-8.narration
      .content
        p
          = @task.content.html_safe

.container
  .row
    .col-xs-12.col-sm-12.col-md-8.col-lg-8
      - flash.each do |key, value|
        - if key == "error"
          = content_tag :div, value, class: "alert alert-danger"
.container
  .row
    div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"
      .task
        p
          = simple_form_for :passing, url: passings_path, id: 'test-form', method: :post do |f|
            = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
            = f.input :task_id, as: :hidden, input_html: { value: @task.id }
            - @task.questions.each_with_index do |question, index|
              = "#{index+1}. #{question.text}"
              - if question.question_type == "OptionQuestion"
                = f.input :answers, as: :check_boxes, label_method: :text, value_method: :id, collection: question.answer_options.shuffle, label: false

            = f.button :submit, "Закончить", class: "btn btn-info btn-lg"
        - if @task.timer.persisted?
          = hidden_field_tag :current_time, DateTime.current
          = hidden_field_tag :attempt_time, @attempt.created_at.to_datetime
          = hidden_field_tag :timer_value_in_seconds, @task.timer.value_in_minutes.minutes

footer
  .container
    .row
      .col-xs-12.col-sm-10.col-md-8.col-lg-8
        .foottext
          p
            | Прогресс по курсу&nbsp;
            span
              = @task.episode.title
          .progress
            div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: #{current_user.progress(@task.episode)}%;"

app/views/tasks/show.html.slim
- if @task.questions.present? && !@task.completed?(current_user)
  .container.alerts
    .row
      .col-lg-12
        .bs-component
          - if @task.timer.persisted?
            div id="time-left"
              .alert.alert-danger.alert-dismissible.text-center
                button type="button" class="close" data-dismiss="alert"&times;
                p
                  | Внимание! Это задание на время. На выполнение у вас &nbsp;
                  strong
                    span.show-time-in-hours
                    span.show-time-in-minutes
                    span.show-time-in-seconds
            div id="time-is-out"
              .alert.alert-danger.alert-dismissible.text-center
                button type="button" class="close" data-dismiss="alert"&times;
                p
                  | К сожалению,&nbsp;
                  strong
                    | время на выполнение истекло.&nbsp;


.container
  .row
    .col-xs-12.col-sm-10.col-md-8.col-lg-8
      h2
        |Лекция&nbsp;
        = @task.position
        |.&nbsp;
        = @task.title

.container
  .row
    .col-xs-12.col-sm-10.col-md-8.col-lg-8.narration
      .content style='width: 1130px'
        p
          = @task.content.html_safe

.container
  .row
    .col-xs-12.col-sm-12.col-md-8.col-lg-8
      - flash.each do |key, value|
        - if key == "error"
          = content_tag :div, value, class: "alert alert-danger"
- if @task.completed?(current_user) && @task.timer.persisted?
  .container
    .row
      div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"
        .task
          h4 Вы уже проходили этот тест
          = link_to 'Назад', :back, class: 'btn btn-success'
- elsif @task.questions.present?
  .container
    .row
      div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"
        .task
          p
            = simple_form_for :passing, url: passings_path, method: :post do |f|
              = f.input :user_id, as: :hidden, input_html: {value: current_user.id}
              = f.input :task_id, as: :hidden, input_html: {value: @task.id}
              - session[:questions].each_with_index do |question, index|
                = "#{index+1}. #{question.text}"
                - if question.question_type == "OptionQuestion"
                  = f.input :answers, as: :check_boxes, label_method: :text, value_method: :id, collection: question.answer_options.shuffle, label: false

              = f.button :submit, "Закончить", class: "btn btn-info btn-lg", id: 'test-submit'
            - if @task.timer.persisted?
              = hidden_field_tag :current_time, DateTime.current
              = hidden_field_tag :attempt_time, @attempt.created_at.to_datetime
              = hidden_field_tag :timer_value_in_seconds, @task.timer.value_in_minutes.minutes
- elsif @task.questions.blank?
  .container
    .row
      div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"
        = link_to 'Назад', :back, class: 'btn btn-success'