config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'contacts' => 'pages#contacts'
  get 'caution' => 'pages#caution'
  resources :passings, only: %i(create) do
    get :results, action: :results, on: :member
  end

  resources :letters, only: %i(create)
  resources :questions, only: [] do
    resources :option_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :text_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :encouraged_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :attachment_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end
  end

  resources :episodes, only: [:index, :show] do
    resources :pages, only: [] do
      get :wait, on: :collection
    end
  end

  resources :tasks, only: [:show] do
    get :current, action: :current, on: :collection
  end

  resources :pages, only: [] do
    get :success, action: :success, on: :collection
    get :excuse, action: :excuse, on: :collection
    get :rules, action: :rules, on: :collection
  end



  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  authenticated :user do
    root "episodes#index", as: :authenticated_root
  end

  root to: 'pages#rules'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy
  has_many :passings, through: :tasks

  has_many :accesses, dependent: :destroy
  has_many :users, through: :accesses

  scope :inactive, -> { where("start_at > ?", DateTime.current) }
  scope :active, -> { where("start_at < ? OR start_at is NULL", DateTime.current) }

  acts_as_list

  scope :current, lambda { |user|
    return completed(user).last.lower_item if completed(user).present?

    first
  }

  def completed?(user)
    tasks.size > 0 && tasks.completed(user).size == tasks.size
  end

  def current?(user)
    higher_item && higher_item.completed?(user) || first?
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
    @active_episodes = current_user.episodes.where('until_at > ?', DateTime.now)
  end

  def show
    @episode = Episode.find(params[:id])
    @tasks = @episode.tasks.all
  end
end

app/views/episodes/index.html.slim
doctype html
html
  head
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    title Outline &mdash; A Free HTML5 Responsive Template by FREEHTML5.CO
    /! Google Webfonts
    link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" /
    link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&subset=cyrillic,cyrillic-ext" rel="stylesheet" /
    css:
       * {
       font-family: 'Open Sans', sans-serif;

      }

      .button {
       border-radius: 5px;
       background-color: #99cc66;
       color: #fff;
       padding: 10px;
       display: inline-block;
       transition: 0.3s ease-out;
       cursor: pointer;

      }


      .box_title {
       font-size: 28px;
       color: #000000;
       margin-left: 35px;
      }

      a {
        color: black;
        text-decoration: none;
      }

      .box_description {
       font-size: 16px;
       color: #777;
       font-weight: 300;
       margin-top: 10px;
       margin-left: 35px;
       margin-right: 35px;
      }

      .box {
       padding: 20px;
       width: 1130px;
       display: inline-block;
       border-radius: 6px;
       border: 1px solid #ddd;
       box-shadow: 0px 0px 14px rgba(0, 0, 0, 0.1);
       margin-bottom: 30px;
       margin-top: 20px;
      }

      .box:hover{
        box-shadow: 0px 0px 14px rgba(0, 0, 0, 0.33);
      }

      .align {
       text-align: right;
       margin-top: 20px;

      }
  body
    .col-xs-12.col-sm-12.col-md-8.col-lg-8 style='display: flex; justify-content: center; align-items: center;'
      .task
        h2 Добро пожаловать в систему дистанционного обучения МАОТ !
        br/
        h5 Сообщите нам об успешной регистрации в системе для получения доступа к программам обучения
        br/
        h6 Телефон для связи 8 (843) 526-60-41, e-mail для связи: maot.kazan@mail.ru
        br/
        
          
    - @active_episodes.each do |episode|
      .container style='margin-top: 25px'
        .box
          .box_title = link_to episode_path(episode) do
            = episode.position
            | .&nbsp
            = episode.title
          .box_description = episode.content.html_safe
          .align
            = link_to 'Пройти обучение', episode_path(episode), class: 'btn btn-success'

/- @active_episodes.each do |episode|
/  .container
/    .row
/      .col-xs-12.col-sm-12.col-md-12.col-lg-12
/        h2
/          | Курс&nbsp;
/          = episode.position
/          | .&nbsp;
/          = episode.title
/
/    .row
/      .col-xs-12.col-sm-8.col-md-8.col-lg-6.narration
/        p
/          = episode.content.html_safe

    /.row
    /  .col-xs-12.col-sm-10.col-md-10.col-lg-10.navigation
    /    table class="table table-hover mytable"
    /      tbody
    /        - episode.tasks.each do |task|
    /          - if task.completed?(current_user)
    /            tr class="checked"
    /              th scope="row"
    /              td
    /                | §&nbsp;
    /                = task.position
    /                | .&nbsp;
    /                = link_to task.title, task_path(task)
    /
    /          - else
    /            tr
    /              th scope="row"
    /              td
    /                | §&nbsp;
    /                = task.position
    /                | .&nbsp;
    /                = link_to task.title, task_path(task)
/
/
/- @inactive_episodes.each do |episode|
/  .container
/    .row
/      .col-xs-12.col-sm-12.col-md-12.col-lg-12
/        h2.light-grey
/          | Эпизод&nbsp
/          = episode.position
/          | .&nbsp
/          = episode.title

app/views/episodes/show.slim
.container
  .row style='margin-left: 300px; margin-top: 30px'
    .col-xs-12.col-sm-10.col-md-8.col-lg-8
      h2
        | Курс&nbsp;
        |:&nbsp;
        = @episode.title
.container style='margin-top: 20px'
  .row
    .col-xs-12.col-sm-10.col-md-10.col-lg-10.navigation
      table class="table table-hover mytable"
        tbody
          - @tasks.each do |task|
            - if task.completed?(current_user)
              tr class="checked"
                th scope="row"
                td
                  | §&nbsp;
                  = task.position
                  | .&nbsp;
                  = link_to task.title, task_path(task), style: 'color: black; text-decoration: none;'
            - elsif task.main
              tr
                th scope="row"
                td
                  | §&nbsp;
                  = task.position
                  | .&nbsp;
                  = link_to task.title, caution_path(task_id: task.id), style: 'color: black; text-decoration: none'
            - else
              tr
                th scope="row"
                td
                  | §&nbsp;
                  = task.position
                  | .&nbsp;
                  = link_to task.title, task_path(task), style: 'color: black; text-decoration: none'
  = link_to 'На главную', episodes_path, class: 'btn btn-success'