config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'contacts' => 'pages#contacts'
  get 'caution' => 'pages#caution'
  resources :passings, only: %i(create) do
    get :results, action: :results, on: :member
  end

  resources :letters, only: %i(create)
  resources :questions, only: [] do
    resources :option_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :text_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :encouraged_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :attachment_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end
  end

  resources :episodes, only: [:index, :show] do
    resources :pages, only: [] do
      get :wait, on: :collection
    end
  end

  resources :tasks, only: [:show] do
    get :current, action: :current, on: :collection
  end

  resources :pages, only: [] do
    get :success, action: :success, on: :collection
    get :excuse, action: :excuse, on: :collection
    get :rules, action: :rules, on: :collection
  end



  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  authenticated :user do
    root "episodes#index", as: :authenticated_root
  end

  root to: 'pages#rules'
end

app/views/pages/caution.slim
.container
  .row style='margin-top: 50px'
    div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"
      .task 
        h4 Это ИТОГОВОЕ тестирование, подтвердите начало его выполнения
        br
        = link_to 'Приступить', task_path(@task), class: 'btn btn-success'

app/views/pages/contacts.slim
.container
  .row
    div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"
      .task
        h4 Наши контакты
        br
        Полное наименование организации: Межрегиональная ассоциация охраны труда

        Сокращенное наименование организации: МАОТ

        Председатель ассоциации Габдрахманов Фанил Исхакович действует на основании Устава


        Почтовый адрес: 420094, Республика Татарстан, г.Казань, ул.Маршала Чуйкова, дом 15 Б, а/я 66

        Наименование банка:  ПАО «АК БАРС» БАНК г.Казань

        БИК 049205805

        ИНН 1658069483

        КПП 165701001

        ОКПО 93075154

        ОГРН 1051633108295

        р.с 40703810045470000002

        к.с 30101810000000000805


        Тел, факс: (843) 520-75-44/ 526-60-41

app/views/pages/excuse.html.slim
.container
  .row
    div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"
      = raw(@excuse_page.excuse_message)
      = "Время начала: #{l @excuse_page.start_time, format: :event_time}"

app/views/pages/rules.html.slim
doctype html
html lang="en" 
  head
    title Дистанционное обучение по охране труда и пожарно-техническому минимуму| МАОТ Казань
    meta charset="utf-8" /
    meta content="f29e3176f82ed213" name="yandex-verification" /
    meta content=("Дистанционное обучение по охране труда, дистанционное обучение специалиста +по охране труда, обучение охране труда руководителей дистанционно, дистанционное обучение по охране труда в казани") name="keywords" /
    meta content=("Зарегистрируйтесь и самостоятельно пройдите обучение по охране труда без отрыва от производства") name="description" /
    link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&subset=cyrillic,cyrillic-ext" rel="stylesheet" /
    = stylesheet_link_tag 'land/reset.css'
    = stylesheet_link_tag 'land/main'
    = javascript_include_tag 'land/main'
    = favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png'
  body
    header
      .wrapper
        a.logo href="#"
          = image_tag 'logo.svg'
        nav
          ul
            li
              = link_to 'РЕГИСТРАЦИЯ', new_user_registration_url
            li
              = link_to 'ВХОД', new_user_session_url
    /! End Header
    section.billboard
      section.caption
        p.cap_title Система дистанционного обучения
        p.cap_desc
          | Зарегистрируйтесь, получите доступ к курсам
          br/
          |и пройдите обучение без отрыва от производства
          br/
        a.start_btn2 href="http://do.maot16.ru/users/sign_up" 
          | Зарегистрироваться
          i
    /! End billboard
    section.services.wrapper
      h4 Почему именно у нас?
      ul
        li
          = image_tag 's1_icon.png', class: 's_icons'
          h3 Простота и доступность
          p Обучающие материалы максимально понятные и доступные, что позволяет легко разобраться в предмете курса и быстро пройти итоговое тестирование
        li
          = image_tag 's2_icon.png', class: 's_icons'
          h3 В Удобное время
          p Чтобы начать обучение, вам не нужно месяцами ждать, пока наберется группа. Вы сами распределяете время и выбираете темп обучения
        li
          = image_tag 'laptop.png', class: 's_icons'
          h3 Дистанционный формат
          p Вам не нужно приезжать в учебный центр на лекции. Для занятий, сдачи тестов и получения удостворения вам нужен только компьютер и интернет.
    /! End services
    section.work_us
      h4 Результат за 6 шагов
      .work_text
        | Пройти обучение и получить удостоверение можно быстро и просто. Для этого необходимо выполнить следующие шаги
      div style=("clear: both;")
      .work_content
        .work_content_block
          .img
            = image_tag 'step01.png'
          .work_content_block_text
            .work_content_block_text_name
              | 1. Заявка
            .work_content_block_text_desc
              | Свяжитесь с нами и оставьте заявку на дистанционное обучение
        .work_content_block
          .img
            = image_tag 'step02.png'
          .work_content_block_text
            .work_content_block_text_name
              | 2. Договор и счет
            .work_content_block_text_desc
              | После чего мы сформируем счет и договор. Подписание и оплата займет не более 20 минут
        .work_content_block
          .img
            = image_tag 'step04.png'
          .work_content_block_text
            .work_content_block_text_name
              | 3. Доступ к системе
            .work_content_block_text_desc
              | После оплаты Вам будет открыт доступ к соответсвующим программам в нашей системе
      .work_content
        .work_content_block
          .img
            = image_tag 'step05.png'
          .work_content_block_text
            .work_content_block_text_name
              | 4. Обучение
            .work_content_block_text_desc
              | Самостоятельно и без отрыва от производста изучите учебный материал
        .work_content_block
          .img
            = image_tag 'step03.png'
          .work_content_block_text
            .work_content_block_text_name
              | 5. Тестирование
            .work_content_block_text_desc
              | Пройдите в системе итоговое тестирование по курсу
        .work_content_block
          .img
            = image_tag 'step06.png'
          .work_content_block_text
            .work_content_block_text_name
              | 6. Удостоверение
            .work_content_block_text_desc
              | Получите удостоверение государственного образца любым удобным для Вас способом
    /! End work_us
    section.subscription
      .wrapper
        p.title Оставьте заявку на обратный звонок
        p.desc Мы с удовольсвтием поможем во всем Вам разобраться
        a.start_btn href="#"  Оставить заявку
    /! End subscription
    section.documentation
      .doc_tit
        | Лицензии
      br/
      .doc_desc
        | Лицензия Министерства образования и науки Республики Татарстан № 5473 от 10 апреля 2014 года
      .documentation_content
        = image_tag 'license1.jpg'
        = image_tag 'license2.jpg'
        = image_tag 'license3.jpg'
    /! End documentaton
    footer
      .wrapper
        .f_cols
          h3 Контакты
          p
            | 420094, г.Казань,
            br/
            | ул.Маршала Чуйкова 15Б
            span.phone (843) 526-60-41
          a.map href="https://yandex.ru/maps/43/kazan/?mode=search&ol=geo&ouri=ymapsbm1%3A%2F%2Fgeo%3Fll%3D49.114594%252C55.836707%26spn%3D0.001%252C0.001%26text%3D%25D0%25A0%25D0%25BE%25D1%2581%25D1%2581%25D0%25B8%25D1%258F%252C%2B%25D0%25A0%25D0%25B5%25D1%2581%25D0%25BF%25D1%2583%25D0%25B1%25D0%25BB%25D0%25B8%25D0%25BA%25D0%25B0%2B%25D0%25A2%25D0%25B0%25D1%2582%25D0%25B0%25D1%2580%25D1%2581%25D1%2582%25D0%25B0%25D0%25BD%252C%2B%25D0%259A%25D0%25B0%25D0%25B7%25D0%25B0%25D0%25BD%25D1%258C%252C%2B%25D1%2583%25D0%25BB%25D0%25B8%25D1%2586%25D0%25B0%2B%25D0%259C%25D0%25B0%25D1%2580%25D1%2588%25D0%25B0%25D0%25BB%25D0%25B0%2B%25D0%25A7%25D1%2583%25D0%25B9%25D0%25BA%25D0%25BE%25D0%25B2%25D0%25B0%252C%2B15%25D0%2591&ll=49.114588%2C55.836706&z=16"
            | посмотреть на карте
            span.arrow &nbsp;&rarr;
        .f_cols
          h3 Ассоциация
          ul
            li
              a href="#"  О нас
            li
              a href="#"  Услуги
            li
              a href="#"  Инфоцентр
        .f_cols
          h3 Поддержка
          ul
            li
              a href="#"  Вопросы и ответы
            li
              a href="#"  Contact Us
            li
              a href="#"  Policies
        .f_cols
          h3 Информация
          p Копирование и переработка любых материалов этого сайта для публичного использования их (размещение на других сайтах, публикации в печатных изданиях, и проч.) разрешается исключительно при получени письменного согласия от автора на копирование материалов
    /! End footer
    /#lightbox
    /#box
    /  a.close href="" style='opacity: 1;'
    /  form action="" method=""
    /    input#name placeholder="Имя" type="text" /
    /    input#phone placeholder="Телефон" type="text" /
    /    select name="courses" required=""
    /      option value="null"  Укажите интересующую программу
    /      option value="1"  Охрана труда
    /      option value="2"  ПТМ
    /    input#submit type="submit" value=("Оставить заявку") /
    #lightbox
    #box
      a.close href="" style='opacity: 1;'
      = simple_form_for :letter, url: letters_path, :method => :post do |f|
        = f.input :name, label: false, placeholder: 'Имя', input_html: { id: 'name' }
        = f.input :phone, label: false, placeholder: 'Телефон', input_html: { id: 'phone' }
        = f.input :course, collection: ['Охрана труда', 'ПТМ'], include_blank: true, label: 'Укажите интересующую программу'

        = f.button :submit, 'Оставить заявку', id: 'submit'
    #descriptbox
    #dbox
      a.close href=""  style='opacity: 1;'
      | О КУРСЕ:
      br/
      | Основными целями курса являются:
      br/
      |  — Обеспечение надлежащей охраны труда на предприятии в целом
      br/
      |  — Обучение специалистов и руководителей организаций и предприятий требованиям охраны труда
      br/
      |  — Формирование необходимых знаний для сокращения роста профессиональных заболеваний и производственного травматизма
      br/
      br/
      |Курс предназначен для специалистов и руководителей организаций, предприятий и учреждений.
      br/
      br/
      |  Итоговый контроль знаний проводится в виде тестирования с последующей выдачей удостоверения о проверке знаний требований охраны труда.
      

app/views/pages/success.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 ">
      <h2>Поздравляем! Вы прошли все курсы</h2>
    </div>
  </div>
</div>

app/views/pages/wait.html.slim
.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      p Спасибо!
      p Вы прошли все существующие эпизоды.
      p
        | Новые задания будут доступны&nbsp;
        =l @episode.start_at, format: :event_time if @episode.start_at

      p
        | Вы можете посмотреть список &nbsp;
        = link_to "выполненных заданий", episodes_url