config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'contacts' => 'pages#contacts'
  get 'caution' => 'pages#caution'
  resources :passings, only: %i(create) do
    get :results, action: :results, on: :member
  end

  resources :letters, only: %i(create)
  resources :questions, only: [] do
    resources :option_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :text_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :encouraged_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end

    resources :attachment_answers, only: [] do
      post :answer, action: :answer, on: :collection
    end
  end

  resources :episodes, only: [:index, :show] do
    resources :pages, only: [] do
      get :wait, on: :collection
    end
  end

  resources :tasks, only: [:show] do
    get :current, action: :current, on: :collection
  end

  resources :pages, only: [] do
    get :success, action: :success, on: :collection
    get :excuse, action: :excuse, on: :collection
    get :rules, action: :rules, on: :collection
  end



  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  authenticated :user do
    root "episodes#index", as: :authenticated_root
  end

  root to: 'pages#rules'
end

app/models/letter.rb
class Letter < ActiveRecord::Base
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController

  def create
    letter = Letter.new(letter_params)
    if letter.save
      LetterMailer.order(letter).deliver_now
      redirect_to root_path
    else
      redirect_to new_user_registration_path
    end
  end

  private

  def letter_params
    params.require(:letter).permit(:name, :phone, :course)
  end
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/letters/_new_letter.html.slim
#lightbox
  #box
    a.close href="" style='opacity: 1;'
      = simple_form_for :letter, url: new_letter_path, method: :post do |f|
        = f.input :name, placeholder: 'Имя', id: 'name'
        = f.input :phone, placeholder: 'Телефон', id: 'phone'
        = f.input :course, collection: ['Охрана труда', 'ПТМ'], include_blank: true, label: 'Укажите интересующую программу'

        = f.submit 'Оставить заявку', id: 'submit'

app/views/letters/new.html.slim
= render 'letters/new_letter'